version: "3.8"

services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/development/backend.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
    environment:
      - ENVIRONMENT=development
    networks:
      - app-network

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/development/frontend.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
