services:
  # Frontend (Static Site)
  - type: static
    name: the-way-forward
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://the-way-forward-api.onrender.com
    branch: main

  # Backend (Web Service)
  - type: web
    name: the-way-forward-api
    env: docker
    dockerfilePath: docker/production/backend.dockerfile
    dockerContext: backend
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
    plan: starter
    region: ohio
    numInstances: 1
    healthCheckPath: /
    branch: main
