version: "3.8"

services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/production/backend.dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/production/frontend.dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
